version: '2'
services:
  db-auth:
    build: ../db-auth
    container_name: db-auth
    networks:
      - authnet
    volumes:
      - db-auth-data:/var/lib/mysql

  userauth:
    build: ../users
    container_name: userauth
    environment:
       DEBUG: "users:*"
       PORT: "3333"
       SEQUELIZE_CONNECT: "sequelize-docker-mysql.yaml"
       REST_LISTEN: "0.0.0.0"
       API_CONFIG: config/api-config.yaml
    networks:
      - authnet
      - notesauth
    expose:
      - 3333
    depends_on:
      - db-auth
    restart: always

  db-notes:
    build: ../db-notes
    container_name: db-notes
    networks:
      - frontnet
    volumes:
      - db-notes-data:/var/lib/mysql

  notesapp:
    build: ../notes
    container_name: notesapp
    networks:
      - frontnet
      - notesauth
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - db-notes
      - userauth
    restart: always
    environment:
      NODE_ENV: "production"
      REQUEST_LOG_FORMAT: "common"
      REQUEST_LOG_FILE: "access.log"
      NOTES_MODEL: MYSQL
      SEQUELIZE_CONNECT: models/note/storage/sequelize/sequelize-docker-mysql.yaml
      USERS_MODEL: models/users-rest
      USER_SERVICE_URL: http://userauth:3333/
      DEBUG: "note-app:*, messages:*"
      NOTES_SESSIONS_DIR: "/sessions"

networks:
  authnet:
    driver: bridge
  frontnet:
    driver: bridge
  notesauth:
    driver: bridge

volumes:
  db-auth-data:
  db-notes-data: